# -*- coding: utf-8 -*-
"""UIII act4 Funciones Diccionario Alexandro 0007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sw-XsgyK_Z6iXHjrxkpL9yPtMxZLFVGN

#### Alexandro Aguilar NL = 1 Fecha 13/Mayo/2026
### diccionarios utilizando  funciones + infografia  en chatGPT
"""

# Diccionario global para almacenar los registros de los médicos
base_datos_medicos = {}

def agregar_medico():
    licencia = input("Ingrese la Licencia profesional (ID único): ")
    if licencia in base_datos_medicos:
        print("Error: El médico ya existe.")
        return

    datos = {
        "especialidad": input("Especialidad: "),
        "hospital": input("Hospital de adscripción: "),
        "experiencia": input("Años de experiencia: "),
        "pacientes": input("Pacientes atendidos: "),
        "turno": input("Turno: ")
    }
    base_datos_medicos[licencia] = datos
    print("Médico agregado con éxito.")

def Listar_medico():
    print("\n" + "="*85)
    print(f"{'LICENCIA':<15} | {'ESPECIALIDAD':<20} | {'HOSPITAL':<20} | {'EXP':<5} | {'TURNO':<10}")
    print("-" * 85)

    if not base_datos_medicos:
        print(f"{'La base de datos está vacía.':^85}")
    else:
        for licencia, info in base_datos_medicos.items():
            # El formato :<N alinea a la izquierda con un espacio de N caracteres
            print(f"{licencia:<15} | {info['especialidad']:<20} | {info['hospital']:<20} | {info['experiencia']:<5} | {info['turno']:<10}")

    print("="*85 + "\n")

def buscar_medico():
    licencia = input("Ingrese la licencia a buscar: ")
    medico = base_datos_medicos.get(licencia)
    if medico:
        print(f"Resultado: {medico}")
    else:
        print("Médico no encontrado.")

def borrar_medico():
    licencia = input("Ingrese la licencia del médico a eliminar: ")
    if licencia in base_datos_medicos:
        del base_datos_medicos[licencia]
        print(f"Registro {licencia} eliminado.")
    else:
        print("No se encontró el registro.")

def actualizar_medico():
    licencia = input("Ingrese la licencia del médico a actualizar: ")
    if licencia in base_datos_medicos:
        print("Ingrese los nuevos datos (deje vacío para mantener el actual):")
        datos_actuales = base_datos_medicos[licencia]

        especialidad = input(f"Especialidad [{datos_actuales['especialidad']}]: ") or datos_actuales['especialidad']
        hospital = input(f"Hospital [{datos_actuales['hospital']}]: ") or datos_actuales['hospital']
        turno = input(f"Turno [{datos_actuales['turno']}]: ") or datos_actuales['turno']

        base_datos_medicos[licencia].update({
            "especialidad": especialidad,
            "hospital": hospital,
            "turno": turno
        })
        print("Registro actualizado correctamente.")
    else:
        print("El médico no existe.")

# Menú interactivo
while True:
    print("--- SISTEMA MÉDICO INTERACTIVO ---")
    print("1. Agregar médico | 2. Listar médicos | 3. Buscar médico")
    print("4. Actualizar médico | 5. Borrar médico | 6. Salir")

    opcion = input("Seleccione una opción (1-6): ")

    if opcion == '1':
        agregar_medico()
    elif opcion == '2':
        Listar_medico()
    elif opcion == '3':
        buscar_medico()
    elif opcion == '4':
        actualizar_medico()
    elif opcion == '5':
        borrar_medico()
    elif opcion == '6':
        print("Saliendo del programa...")
        break

print("Programa realizado por Alexandro Aguilar")

"""![Info](https://raw.githubusercontent.com/alexandroaguilar128/UIII-act4-funciones-diccionario-Alexandro-0007/refs/heads/main/ACT4infografiadiccionariofunciones.png)"""